# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancePartnerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alliance_code', models.CharField(blank=True, max_length=20, null=True)),
                ('order_status', models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, b'PENDING'), (2, b'PAID')], default=1)),
                ('amount', models.FloatField(verbose_name='Order Amount (\u20b9)')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='Tax (\u20b9)')),
                ('discount_amount', models.FloatField(default=0, verbose_name='Discount Amount (\u20b9)')),
                ('promo_code', models.CharField(blank=True, max_length=55, null=True)),
                ('total_amount', models.FloatField(verbose_name='Total Amount (\u20b9)')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_order', models.IntegerField(blank=True, choices=[(1, b'Shakti Cancelled the order'), (2, b'Credit Block'), (3, b'Delivery Delayed'), (4, b'Incorrect Order'), (5, b'Other')], null=True, verbose_name='Reason for cancellation')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enter your reason')),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apo_allianceuser_related', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apo_distributoruser_related', to=settings.AUTH_USER_MODEL, verbose_name='Redistribution Stockist')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress')),
            ],
            options={
                'verbose_name': 'Primary Order',
                'verbose_name_plural': 'Primary Orders',
            },
        ),
        migrations.CreateModel(
            name='AlliancePartnerOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('dispatch_quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.FloatField(help_text='Net rate from Products table', verbose_name='AIP (\u20b9)')),
                ('price', models.FloatField(verbose_name='Price (\u20b9)')),
                ('item_status', models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1)),
                ('alliance_partner_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.AlliancePartnerOrder')),
            ],
            options={
                'verbose_name': 'Primary Order Detail',
                'verbose_name_plural': 'Primary Order Details',
            },
        ),
        migrations.CreateModel(
            name='DistributorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_status', models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, b'PENDING'), (2, b'PAID')], default=1)),
                ('amount', models.FloatField(verbose_name='Order Amount (\u20b9)')),
                ('tax', models.FloatField(default=0, verbose_name='Tax (\u20b9)')),
                ('discount_amount', models.FloatField(default=0, verbose_name='Discount Amount (\u20b9)')),
                ('promo_code', models.CharField(blank=True, max_length=55, null=True)),
                ('total_amount', models.FloatField(verbose_name='Total Amount (\u20b9)')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_order', models.IntegerField(blank=True, choices=[(1, b'Shakti Cancelled the order'), (2, b'Credit Block'), (3, b'Delivery Delayed'), (4, b'Incorrect Order'), (5, b'Other')], null=True, verbose_name='Reason for cancellation')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enter your reason')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_distributor_related', to=settings.AUTH_USER_MODEL, verbose_name='Redistribution Stockist')),
                ('sales_promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_salespromoter_related', to=settings.AUTH_USER_MODEL, verbose_name='RSP')),
                ('shakti_enterpreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_shaktientrepreneur_related', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress')),
            ],
            options={
                'verbose_name': 'Secondary Order',
                'verbose_name_plural': 'Secondary Orders',
            },
        ),
        migrations.CreateModel(
            name='DistributorOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('dispatch_quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.FloatField(verbose_name='AIP (\u20b9)')),
                ('price', models.FloatField(help_text='TUR price from product', verbose_name='Price (\u20b9)')),
                ('is_cld', models.BooleanField(default=False)),
                ('item_status', models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1)),
                ('distributor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor_order_details', to='orders.DistributorOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributororderdetail', to='product.Product')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress')),
            ],
            options={
                'verbose_name': 'Secondary Order Detail',
                'verbose_name_plural': 'Secondary Order Details',
            },
        ),
        migrations.CreateModel(
            name='DistributorStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributorstock', to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='distributor_order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DistributorOrderDetail'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliancepartnerorderdetail', to='product.Product'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
    ]
