# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170220_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('delievered', 'DELIEVERED'), ('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('dispatched', 'DISPATCHED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='payment_status',
            field=models.CharField(choices=[('received', 'RECEIVED'), ('paid', 'PAID'), ('pending', 'PENDING')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='item_status',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('delievered', 'DELIEVERED'), ('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('dispatched', 'DISPATCHED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('delievered', 'DELIEVERED'), ('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('dispatched', 'DISPATCHED')], default='confirmed', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='payment_status',
            field=models.CharField(choices=[('received', 'RECEIVED'), ('paid', 'PAID'), ('pending', 'PENDING')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='item_status',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('delievered', 'DELIEVERED'), ('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('dispatched', 'DISPATCHED')], default='pending', max_length=10),
        ),
    ]
