# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170220_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSearch',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Advance Search',
            },
            bases=('orders.distributororder',),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='payment_status',
            field=models.IntegerField(choices=[(1, b'PENDING'), (2, b'PAID')], default=1),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='item_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='order_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='payment_status',
            field=models.IntegerField(choices=[(1, b'PENDING'), (2, b'PAID')], default=1),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='item_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED'), (8, b'DISCARDED')], default=1),
        ),
    ]
