# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170427_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancePartnerDistributorOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Other Primary Order Details',
            },
            bases=('orders.alliancepartnerorderdetail',),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED')], default=1),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='distributor_order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DistributorOrderDetail'),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='item_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (6, b'DELIVERED')], default=1),
        ),
    ]
