# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-18 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170711_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorstock',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount (\u20b9)'),
        ),
    ]
