# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
        ('product', '0004_auto_20180711_0940'),
        ('app', '0010_auto_20180711_0940'),
        ('orders', '0009_distributorstock_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancePartnerDiscountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_name', models.CharField(
                    blank=True, max_length=150, null=True)),
                ('total_quantity', models.IntegerField()),
                ('discount_amount', models.FloatField(
                    verbose_name='Discount Amount (\u20b9)')),
            ],
            options={
                'verbose_name': 'Primary Order Discount Detail',
                'verbose_name_plural': 'Primary Order Discount Details',
            },
        ),
        migrations.CreateModel(
            name='AlliancePartnerShaktiDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_amount', models.FloatField(
                    verbose_name='Discount Amount (\u20b9)')),
            ],
            options={
                'verbose_name': 'Primary Order Shakti Discount Detail',
                'verbose_name_plural': 'Primary Order Shakti Discount Details',
            },
        ),
        migrations.CreateModel(
            name='ReviewPrimaryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0,
                                             verbose_name='Order Amount (\u20b9)')),
                ('tax', models.FloatField(default=0, verbose_name='Tax (\u20b9)')),
                ('discount_amount', models.FloatField(
                    default=0, verbose_name='Discount Amount (\u20b9)')),
                ('promo_code', models.CharField(
                    blank=True, max_length=55, null=True)),
                ('total_amount', models.FloatField(
                    verbose_name='Total Amount (\u20b9)')),
                ('is_placed', models.BooleanField(default=False)),
                ('is_discarded', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='rpo_distributoruser', to=settings.AUTH_USER_MODEL, verbose_name='Redistribution Stockist')),
                ('shipping_address', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress')),
            ],
            options={
                'verbose_name': 'Review Primary Order',
                'verbose_name_plural': 'Review Primary Orders',
            },
        ),
        migrations.CreateModel(
            name='ReviewPrimaryOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alliance_code', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(
                    verbose_name='Quantity (in cases)')),
                ('order_generated', models.IntegerField(
                    verbose_name='Order Generated (in cases)')),
                ('unitprice', models.FloatField(
                    help_text='base price from Products table', verbose_name='Base Price (\u20b9)')),
                ('price', models.FloatField(
                    help_text='base price * quantity', verbose_name='Price (\u20b9)')),
                ('cgst_amount', models.FloatField(
                    default=0, verbose_name='CGST Amount (\u20b9)')),
                ('sgst_amount', models.FloatField(
                    default=0, verbose_name='SGST Amount (\u20b9)')),
                ('igst_amount', models.FloatField(
                    default=0, verbose_name='IGST Amount (\u20b9)')),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='rpo_allianceuser', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('review_primary_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orders.ReviewPrimaryOrder', null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.DeleteModel(
            name='AdvanceSearch',
        ),
        migrations.RemoveField(
            model_name='alliancepartnerorderdetail',
            name='distributor_order_detail',
        ),
        migrations.RemoveField(
            model_name='alliancepartnerorderdetail',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='distributororder',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='claim_status',
            field=models.IntegerField(
                choices=[(0, b'NA'), (1, b'PENDING'), (2, b'PROCESSED')], default=0),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='dispatched_on',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Dispatched On'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='has_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='invoice_number_alliance',
            field=models.CharField(
                blank=True, help_text='This is received from Alliance csv', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='order_id',
            field=models.IntegerField(null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='add_discount',
            field=models.FloatField(
                default=0, help_text='Additional discount given for customer'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='asch_discount',
            field=models.FloatField(
                default=0, help_text='Additional scheme discount'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='cash_discount',
            field=models.FloatField(default=0, help_text='Cash Discount'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='cess',
            field=models.FloatField(default=0, verbose_name='Cess (%)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='cess_amount',
            field=models.FloatField(
                default=0, verbose_name='Cess Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='cgst',
            field=models.FloatField(default=0, verbose_name='CGST (%)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='cgst_amount',
            field=models.FloatField(
                default=0, verbose_name='CGST Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='discount_amount',
            field=models.FloatField(
                default=0, verbose_name='Discount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='disp_discount',
            field=models.FloatField(
                default=0, help_text='Disposable item discount'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='dispatched_on',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Dispatched On'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='igst',
            field=models.FloatField(default=0, verbose_name='IGST (%)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='igst_amount',
            field=models.FloatField(
                default=0, verbose_name='IGST Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='prd_discount',
            field=models.FloatField(
                default=0, help_text='This value is discount given in products'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='product_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='sch_discount',
            field=models.FloatField(default=0, help_text='Scheme Discount'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='sgst',
            field=models.FloatField(default=0, verbose_name='SGST (%)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='sgst_amount',
            field=models.FloatField(
                default=0, verbose_name='SGST Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='trade_discount',
            field=models.FloatField(default=0, help_text='Trade Discount'),
        ),
        migrations.AddField(
            model_name='distributororder',
            name='dispatched_on',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Dispatched On'),
        ),
        migrations.AddField(
            model_name='distributororder',
            name='promotion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(
                blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='cgst',
            field=models.FloatField(default=0, verbose_name='CGST (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='discount_amount',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Discount Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='dispatched_on',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Dispatched On'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='distributor_discount',
            field=models.FloatField(
                default=0, help_text='Scheme Discount by Stockist', verbose_name='Discount to Shakti (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='distributor_discount_percent',
            field=models.FloatField(
                default=0, help_text='Scheme Discount in Percentage by Stockist', verbose_name='Discount to Shakti (\u20b9%)'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='distributor_promotion',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.DiscountToShakti'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='igst',
            field=models.FloatField(default=0, verbose_name='IGST (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='net_amount',
            field=models.FloatField(
                default=1, help_text='taxable amount + taxes * stockist margin', verbose_name='Net Amount (\u20b9)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='product_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='promotion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(
                blank=True, null=True), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='promotion_applied',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributororderdetail',
            name='sgst',
            field=models.FloatField(default=0, verbose_name='SGST (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='order_status',
            field=models.IntegerField(choices=[(
                1, b'ORDERED'), (10, b'IN TRANSIT'), (7, b'CANCELLED'), (6, b'RS RECEIVED')], default=1),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='tax',
            field=models.FloatField(default=0, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='item_status',
            field=models.IntegerField(choices=[(
                1, b'ORDERED'), (10, b'IN TRANSIT'), (7, b'CANCELLED'), (6, b'RS RECEIVED')], default=1),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='unitprice',
            field=models.FloatField(
                help_text='base price from Products table', verbose_name='Base Price (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='order_status',
            field=models.IntegerField(choices=[(
                1, b'ORDERED'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (9, b'RETURNED')], default=1),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='item_status',
            field=models.IntegerField(choices=[(
                1, b'ORDERED'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (9, b'RETURNED')], default=1),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='price',
            field=models.FloatField(
                help_text='Base price * quantity', verbose_name='Price (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='unitprice',
            field=models.FloatField(verbose_name='Base Rate (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='review_primary_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='apo_review_primary', to='orders.ReviewPrimaryOrder', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='alliancepartnerorder',
            unique_together=set([('distributor', 'order_id')]),
        ),
        migrations.AddField(
            model_name='alliancepartnershaktidiscount',
            name='alliance_partner_order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='orders.AlliancePartnerOrder'),
        ),
        migrations.AddField(
            model_name='alliancepartnershaktidiscount',
            name='shakti_bonus_line',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.ShaktiBonusLines'),
        ),
        migrations.AddField(
            model_name='alliancepartnershaktidiscount',
            name='shakti_enterpreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app.ShaktiEntrepreneur', to_field='user'),
        ),
        migrations.AddField(
            model_name='alliancepartnerdiscountdetail',
            name='alliance_partner_order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='orders.AlliancePartnerOrder'),
        ),
        migrations.AddField(
            model_name='alliancepartnerdiscountdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='alliancepartnerdiscountdetail', to='product.Product'),
        ),
    ]
