# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-07-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moc', '__first__'),
        ('orders', '0010_auto_20180711_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewprimaryorder',
            options={'verbose_name': 'Primary Order Page', 'verbose_name_plural': 'Primary Orders Page'},
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='moc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_order_moc', to='moc.MoCMonth'),
        ),
        migrations.AddField(
            model_name='distributororder',
            name='moc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_order_moc', to='moc.MoCMonth'),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorder',
            name='amount',
            field=models.FloatField(verbose_name='Gross Amount (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='amount',
            field=models.FloatField(verbose_name='Gross Amount (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_shipping', to='app.UserAddress'),
        ),
    ]
