# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-10-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191014_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributororderdetail',
            name='net_amount',
            field=models.FloatField(help_text='taxable amount + taxes', verbose_name='Net Amount (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributororderdetail',
            name='unitprice',
            field=models.FloatField(help_text='base rate + stockist margin', verbose_name='Base Rate (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
