# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-10-21 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191021_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 6, 4, 17, 809386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 6, 4, 17, 809416, tzinfo=utc)),
        ),
    ]
