# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-01-06 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191021_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 13, 12, 43, 442624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 13, 12, 43, 442656, tzinfo=utc)),
        ),
    ]
