# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-02-21 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 7, 51, 55, 571905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 7, 51, 55, 571935, tzinfo=utc)),
        ),
    ]
