# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-01-14 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200221_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='cgst_total',
            field=models.FloatField(default=0, verbose_name='CGST Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='dis_total',
            field=models.FloatField(default=0, verbose_name='Discount Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='sgst_total',
            field=models.FloatField(default=0, verbose_name='SGST Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorder',
            name='sta_total',
            field=models.FloatField(default=0, verbose_name='Stales Disc Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='base_price_par_unit',
            field=models.FloatField(default=0, verbose_name='Base Price Per Unit (\u20b9)'),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='batch_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='prod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alliancepartnerorderdetail',
            name='total_amt_base_peice',
            field=models.FloatField(default=0, verbose_name='Total Amt (Base price) (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='cash_discount',
            field=models.FloatField(default=0, help_text=' Discount '),
        ),
        migrations.AlterField(
            model_name='alliancepartnerorderdetail',
            name='discount_amount',
            field=models.FloatField(default=0, help_text='Cash Discount', verbose_name='Discount (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 5, 44, 49, 284000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 5, 44, 49, 284000, tzinfo=utc)),
        ),
    ]
