# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-01-22 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220114_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributororder',
            name='cgst_total',
            field=models.FloatField(default=0, verbose_name='CGST Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororder',
            name='igst_total',
            field=models.FloatField(default=0, verbose_name='IGST Total (\u20b9)'),
        ),
        migrations.AddField(
            model_name='distributororder',
            name='sgst_total',
            field=models.FloatField(default=0, verbose_name='SGST Total (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 13, 43, 39, 654000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='distributorstock',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 13, 43, 39, 654000, tzinfo=utc)),
        ),
    ]
