# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-06-12 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220122_1913'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='alliancepartnerorderdetail',
        #     name='invoice_number_alliance',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),

    ]
