# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_distributorstock_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('orders.alliancepartnerorder',),
        ),
    ]
