# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text=b'Note: Maximum 30 character(s).', max_length=30)),
                ('short_description', models.CharField(blank=True, help_text=b'Note: Maximum 250 character(s).', max_length=250)),
                ('logo', s3direct.fields.S3DirectField(blank=True, help_text=b'Image Size should not more than 100kb.', null=True)),
                ('sort_order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner_code', models.CharField(max_length=50)),
                ('basepack_name', models.CharField(max_length=50)),
                ('basepack_code', models.CharField(max_length=50)),
                ('basepack_size', models.CharField(max_length=50)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'SKU')),
                ('expiry_day', models.IntegerField(blank=True, null=True, verbose_name=b'Expire in(days)')),
                ('cld_configurations', models.IntegerField()),
                ('cld_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='CLD Rate (\u20b9)')),
                ('retailer_margin', models.FloatField(blank=True, default=0, help_text=b'Retailer margin is in %', null=True)),
                ('mrp', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='MRP (\u20b9)')),
                ('tur', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='TUR (\u20b9)')),
                ('net_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='AIP (\u20b9)')),
                ('image', s3direct.fields.S3DirectField(help_text=b'Image Size                                      should not more than 300kb.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AlliancePartner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name=b'Category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.MeasurementUnit', verbose_name=b'Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', s3direct.fields.S3DirectField(blank=True, help_text=b'Image Size should not more than 300kb.', null=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
