# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-15 12:03
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, help_text=b'Image Size                                      should not more than 300kb.', null=True),
        ),
    ]
