# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170621_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retailer_margin',
        ),
        migrations.AddField(
            model_name='product',
            name='base_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='Base Price (\u20b9)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cgst',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='CGST (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cgst_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='CGST Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='product',
            name='igst',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='IGST (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='igst_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='IGST Amount (\u20b9)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='SGST (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.99)], verbose_name='SGST Amount (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cld_configurations',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='MRP (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='Invoice Price (\u20b9)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tur',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10000.99)], verbose_name='TUR (\u20b9)'),
        ),
    ]
