# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-09 11:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180711_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cgst',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='CGST (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='igst',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='IGST (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sgst',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='SGST (%)'),
        ),
    ]
