# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-01-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181009_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('child_basepack_code', models.CharField(max_length=50)),
                ('mother_basepack_code', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
