# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-01-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
