# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-05-30 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productchild_en_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
