# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-07-16 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_en_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='en_code',
        ),
    ]
