"""custom constants"""

OAUTH_EXPIRY_SECONDS = 31104000
ECOMM_APPLICATION_NAME = 'HUL-MOBILAPP'
HTTP_USER_ERROR = 111
MESSAGE_KEY = 'message'
TOKEN_KEY = 'token'
SUCCESS_MESSAGE_KEY = 'Success'
ERROR_MESSAGE_KEY = 'Error'
RESPONSE_KEY = 'response'
ERROR_KEY = 'error'
LST_APP_FOR_LOGGING = ['app', 'orders']
HTTP_AUTHORIZATION = 'HTTP_AUTHORIZATION'
STATUS_CODE_KEY = 'status_code'
RESPONSE_KEY = 'response'
EMAIL_LIMIT = 30
OLD_PASSWORD = 'old_password'
NEW_PASSWORD = 'new_password'
DEFAULT_PASSWORD = '123456'
# time in minutes
OTP_EXPIRE_TIME = 5
OTP_KEY = 'otp'
USER_KEY = 'user'

MIN_SORT_ORDER = 1
MAX_SORT_ORDER = 101
USER = 'user'
ACCESSTOKEN = 'access_token'
EMAIL = 'email'
USERNAME = 'username'
PASSWORD = 'password'
MOBILE = 'mobile'
NAME = 'name'
ID = 'id'
IS_DEFAULT = 'is_default'
VALID_EXTENSIONS = ['.jpg', '.png', '.jpeg']
USERTYPE = 'user_type'

TAX = 1
DISCOUNT = 0
PROMOCODE_DISCOUNT = 0
HTTP_INVALID_PASSWORD = 203
ADMIN_PAGE_SIZE = 20
PROMOCODE_DISCOUNT = 0
ADMIN_EMAIL = 'mayank.kukreja@netsolutions.in'
FROM_EMAIL = 'HUL Team <no-reply@hul.com>'
SUBJECT_PREFIX = 'HUL - '
ALLIANCE_EMAIL_SUBJECT = SUBJECT_PREFIX + 'User Registered.'
RESET_EMAIL_SUBJECT = 'Reset Password for your HUL Account'
PRODUCT_LIST_SIZE = 10
SHAKTI_ENTERPERNEUR_LIST_SIZE = 10
ALLIANCE_PARTNER_LIST_SIZE = 10
CATEGORY_LIST_SIZE = 10
ORDER_LIST_SIZE = 10

HTTP_USER_NOT_AUTHENTICATED = 1001
HTTP_USER_ALREADY_REGISTERED = 1002
HTTP_USER_NOT_FOUND = 1003
HTTP_INVALID_OTP = 1004
HTTP_INVALID_PASSWORD = 1005
HTTP_USER_ADDRESS_NOT_FOUND = 1006
HTTP_PRODUCT_NOT_FOUND = 1007
HTTP_ORDER_NOT_FOUND = 1008
HTTP_CART_NOT_FOUND = 1009
HTTP_INVALID_TOKEN = 1010

#time in seconds
SCHEDULER_TIMING = 10
COUNTRY_CODE = '+91'
HTTP_STATUSCODE = 200
LEADING_PAGE_RANGE_DISPLAYED = TRAILING_PAGE_RANGE_DISPLAYED = 10
LEADING_PAGE_RANGE = TRAILING_PAGE_RANGE = 8
NUM_PAGES_OUTSIDE_RANGE = 2
ADJACENT_PAGES = 4
FILE_TYPE_CSV = 'csv'
FILE_TYPE_XLSX = 'xlsx'
DEFAULT_COUNTRY = 'India'

MOC_START_DATE = 21
MOC_END_DATE = 20
MONTHS = [1,2,3,4,5,6,7,8,9,10,11,12]
DISPATCH_DAYS = 15


