# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_distributorstock_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Data',
                'proxy': True,
                'verbose_name_plural': 'Data',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='BasePackLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Base Pack Level',
                'proxy': True,
                'verbose_name_plural': 'Base Pack Level',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='BasepkLevelFormat',
            fields=[
            ],
            options={
                'verbose_name': 'Base Pack Level Format',
                'proxy': True,
                'verbose_name_plural': 'Base Pack Level Format',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='BillCount',
            fields=[
            ],
            options={
                'verbose_name': 'Bill Count Data',
                'proxy': True,
                'verbose_name_plural': 'Bill Count Data',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='RsLevel',
            fields=[
            ],
            options={
                'verbose_name': 'RS Level',
                'proxy': True,
                'verbose_name_plural': 'RS Level',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='RspLevel',
            fields=[
            ],
            options={
                'verbose_name': 'RSP Level',
                'proxy': True,
                'verbose_name_plural': 'RSP Level',
            },
            bases=('orders.distributororder',),
        ),
        migrations.CreateModel(
            name='SeLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Shakti Entrepreneur Level',
                'proxy': True,
                'verbose_name_plural': 'Shakti Entrepreneur Level',
            },
            bases=('orders.distributororder',),
        ),
    ]
