# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 10:38
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, help_text=b'Please enter 10 digit number e.g. 9876543210', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text=b'Designates whether                                   the user can log into this admin site.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', s3direct.fields.S3DirectField(blank=True, help_text=b'Image Size should not more than 300kb.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlliancePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('party_packing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alliance Partner',
                'verbose_name_plural': 'Alliance Partners',
            },
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('otp', models.IntegerField(db_index=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('otp_status_type', models.CharField(choices=[(3, b'ERROR'), (2, b'SUCCESS'), (1, b'VERIFIED'), (4, b'USED'), (0, b'PENDING')], default=0, max_length=250)),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Redistribution Stockist',
                'verbose_name_plural': 'Redistribution Stockists',
            },
        ),
        migrations.CreateModel(
            name='RegionalSalesPromoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rsp_id', models.CharField(max_length=50, verbose_name=b'RSP ID')),
                ('employee_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'RSP',
                'verbose_name_plural': 'RSPs',
            },
        ),
        migrations.CreateModel(
            name='ShaktiEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('beat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_day', models.SmallIntegerField(choices=[(2, b'MONDAY'), (3, b'TUESDAY'), (4, b'WEDNESDAY'), (5, b'THURSDAY'), (6, b'FRIDAY'), (7, b'SATURDAY'), (1, b'SUNDAY')], default=2)),
            ],
            options={
                'verbose_name': 'Shakti Entrepreneur',
                'verbose_name_plural': 'Shakti Entrepreneurs',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address_type', models.CharField(choices=[(b'recepient', b'RECEPIENT'), (b'sender', b'SENDER')], default=b'sender', max_length=100)),
                ('country', models.ForeignKey(db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.IntegerField(choices=[(1, b'Alliance Partner'), (2, b'Regional Distributor'), (3, b'Regional Sales Promoter'), (4, b'Shakti Entrepreneur'), (5, b'Super User')], default=1)),
                ('import_file', models.FileField(upload_to=b'media/import_data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shakti_address', to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='regional_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shakti_rsp', to='app.RegionalSalesPromoter', verbose_name=b'RSP'),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shakti_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='regional_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RegionalDistributor', verbose_name=b'Redistribution Stockist'),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='alliance_partner',
            field=models.ManyToManyField(to='app.AlliancePartner'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alliancepartner',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='alliancepartner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
