# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hul.validators


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '__first__'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('otp_status_type', models.CharField(choices=[(4, 'USED'), (1, 'VERIFIED'), (3, 'ERROR'), (0, 'PENDING'), (2, 'SUCCESS')], default=0, max_length=250)),
                ('expiration_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShaktiEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('beat_name', models.CharField(max_length=100)),
                ('order_day', models.SmallIntegerField(choices=[(2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY'), (7, 'SATURDAY'), (1, 'SUNDAY')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=50)),
                ('address_type', models.CharField(choices=[('sender', 'SENDER'), ('recepient', 'RECEPIENT')], default='sender', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='alliancepartner',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='alliancepartner',
            old_name='updated_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='regionaldistributor',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='regionaldistributor',
            old_name='updated_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='regionalsalespromoter',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='regionalsalespromoter',
            old_name='updated_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alliancepartner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regionaldistributor',
            name='name',
        ),
        migrations.AddField(
            model_name='alliancepartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='alliance_partner',
            field=models.ManyToManyField(to='app.AlliancePartner'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='regional_distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.RegionalDistributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, help_text='Image Size                                      should not more than 300kb.', upload_to='user_images/', validators=[hul.validators.validate_product_image]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alliancepartner',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
        migrations.AlterField(
            model_name='regionalsalespromoter',
            name='rsp_id',
            field=models.CharField(max_length=50, verbose_name='RSP ID'),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shakti_address', to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='regional_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shakti_rsp', to='app.RegionalSalesPromoter', verbose_name='Regional Sales Promoter'),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shakti_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
        migrations.AddField(
            model_name='regionalsalespromoter',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserAddress'),
        ),
    ]
