# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170220_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp_status_type',
            field=models.CharField(choices=[(4, 'USED'), (2, 'SUCCESS'), (1, 'VERIFIED'), (0, 'PENDING'), (3, 'ERROR')], default=0, max_length=250),
        ),
    ]
