# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170220_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shaktientrepreneur',
            options={'verbose_name': 'Shakti Entrepreneur', 'verbose_name_plural': 'Shakti Entrepreneurs'},
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp_status_type',
            field=models.CharField(choices=[(3, b'ERROR'), (2, b'SUCCESS'), (1, b'VERIFIED'), (4, b'USED'), (0, b'PENDING')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regionalsalespromoter',
            name='regional_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RegionalDistributor', verbose_name=b'Redistribution Stockist'),
        ),
        migrations.AlterField(
            model_name='shaktientrepreneur',
            name='beat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shaktientrepreneur',
            name='regional_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shakti_rsp', to='app.RegionalSalesPromoter', verbose_name=b'RSP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, help_text=b'Image Size should not more than 300kb.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
