# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-08 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170427_0607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImport',
        ),
    ]
