# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-24 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170519_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, help_text=b'Recommended image size is 300x300.', null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.State'),
        ),
    ]
