# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180711_0940'),
        ('app', '0009_auto_20170524_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('norm', models.PositiveIntegerField(verbose_name='Norm (in cases)')),
            ],
        ),
        migrations.RemoveField(
            model_name='alliancepartner',
            name='party_packing',
        ),
        migrations.AddField(
            model_name='alliancepartner',
            name='stockist_margin',
            field=models.FloatField(default=b'5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Stockist Margin (in %)'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='ap_dist_channel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alliance Distribution Channel'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='ap_division',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alliance Division'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='ap_plant',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alliance Plant'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Manual Order'),
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='min_order',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Minimum Order (\u20b9)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='order_day',
            field=models.IntegerField(choices=[(2, b'MONDAY'), (3, b'TUESDAY'), (4, b'WEDNESDAY'), (5, b'THURSDAY'), (6, b'FRIDAY'), (7, b'SATURDAY'), (1, b'SUNDAY')], default=2),
        ),
        migrations.AddField(
            model_name='shaktientrepreneur',
            name='min_order',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Minimum Order (\u20b9)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alliancepartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp_status_type',
            field=models.IntegerField(choices=[(3, b'ERROR'), (2, b'SUCCESS'), (1, b'VERIFIED'), (4, b'USED'), (0, b'PENDING')], default=0),
        ),
        migrations.AlterField(
            model_name='regionaldistributor',
            name='alliance_partner',
            field=models.ManyToManyField(related_name='alliance_distributor_related', to='app.AlliancePartner'),
        ),
        migrations.AlterField(
            model_name='regionaldistributor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionalsalespromoter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shaktientrepreneur',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shaktientrepreneur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shakti_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distributornorm',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_norm', to='app.RegionalDistributor'),
        ),
        migrations.AddField(
            model_name='distributornorm',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_norm', to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='distributornorm',
            unique_together=set([('distributor', 'product')]),
        ),
    ]
