# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-07-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180711_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='localization.Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='localization.State'),
        ),
    ]
