# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-02-21 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190716_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaldistributor',
            name='gst_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionaldistributor',
            name='hul_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
