# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-07-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='otp_status_type',
            field=models.IntegerField(choices=[(0, b'PENDING'), (2, b'SUCCESS'), (4, b'USED'), (1, b'VERIFIED'), (3, b'ERROR')], default=0),
        ),
        migrations.AlterField(
            model_name='regionaldistributor',
            name='order_day',
            field=models.IntegerField(choices=[(8, b'---'), (2, b'MONDAY'), (3, b'TUESDAY'), (4, b'WEDNESDAY'), (5, b'THURSDAY'), (6, b'FRIDAY'), (7, b'SATURDAY'), (1, b'SUNDAY')], default=2),
        ),
        migrations.AlterField(
            model_name='shaktientrepreneur',
            name='order_day',
            field=models.SmallIntegerField(choices=[(8, b'---'), (2, b'MONDAY'), (3, b'TUESDAY'), (4, b'WEDNESDAY'), (5, b'THURSDAY'), (6, b'FRIDAY'), (7, b'SATURDAY'), (1, b'SUNDAY')], default=2),
        ),
    ]
