# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-24 06:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_auto_20170519_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default=b'mayank.kukreja@netsolutions.in', max_length=255)),
                ('to_email', models.EmailField(db_index=True, default=b'mayank.kukreja@netsolutions.in', max_length=255)),
                ('carbon_copy', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255), blank=True, null=True, size=None, verbose_name=b'cc')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message', tinymce.models.HTMLField()),
                ('sent_status_type', models.IntegerField(choices=[(4, b'NOTIFICATIONS OFF'), (2, b'INPROGRESS'), (1, b'PENDING'), (3, b'SUCCESS'), (3, b'ERROR')], default=1)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=15, verbose_name=b'Phone Number (Shakti)')),
                ('order_status', models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (6, b'DELIVERED'), (8, b'DISCARDED'), (7, b'CANCELLED')], db_index=True)),
                ('message', models.CharField(max_length=255, verbose_name=b'Message')),
                ('sent_status_type', models.IntegerField(choices=[(4, b'NOTIFICATIONS OFF'), (2, b'INPROGRESS'), (1, b'PENDING'), (3, b'SUCCESS'), (3, b'ERROR')], default=1)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True)),
                ('distributor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DistributorOrder')),
            ],
        ),
    ]
