# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default=b'HUL Team <no-reply@ishaktiapp.com>', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='sent_status_type',
            field=models.IntegerField(choices=[(1, b'PENDING'), (2, b'INPROGRESS'), (3, b'SUCCESS'), (3, b'ERROR'), (4, b'NOTIFICATIONS OFF')], default=1),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='sent_status_type',
            field=models.IntegerField(choices=[(1, b'PENDING'), (2, b'INPROGRESS'), (3, b'SUCCESS'), (3, b'ERROR'), (4, b'NOTIFICATIONS OFF')], default=1),
        ),
    ]
