# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20170707_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default=b'HUL Team <noreply@ishaktiapp.com>', max_length=255),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='order_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (2, b'CONFIRMED'), (3, b'SHIPPED'), (4, b'READY FOR PICKUP'), (5, b'DISPATCHED'), (6, b'DELIVERED'), (7, b'CANCELLED'), (9, b'RETURNED')], db_index=True),
        ),
    ]
