# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170711_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default=b'HUL Team <no-reply@hul.com>', max_length=255),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='order_status',
            field=models.IntegerField(choices=[(1, b'ORDERED'), (5, b'DISPATCHED'), (7, b'CANCELLED'), (9, b'RETURNED')], db_index=True),
        ),
    ]
