# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-11 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_auto_20180711_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayRS',
            fields=[
            ],
            options={
                'verbose_name': "Today's PDP RS",
                'proxy': True,
                'verbose_name_plural': "Today's PDP RS",
            },
            bases=('app.regionaldistributor',),
        ),
        migrations.CreateModel(
            name='TodayShakti',
            fields=[
            ],
            options={
                'verbose_name': "Today's PDP Shakti Entrepreneur",
                'proxy': True,
                'verbose_name_plural': "Today's PDP Shakti Entrepreneurs",
            },
            bases=('app.shaktientrepreneur',),
        ),
    ]
